languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Blowfish"
logo = "img/amohey_logo.png"
logo_dim = "img/amohey_logo_dim.png"
#secondaryLogo = "PATH"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
copyright = "© 2023"

dateFormat = "2 Jan 2006"

[author]
  name = "Ayman Mohey"
  image = "img/blowfish_logo.png"
  headline = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
 links = [
   { facebook = "https://facebook.com/username" },
   { instagram = "https://instagram.com/username" },
   { telegram = "https://t.me/username" },
   { twitter = "https://twitter.com/username" },
 ]
